[settings]
timeout = 1000

[relaychain.runtime_genesis_patch.configuration.config]
max_validators_per_core = 2
needed_approvals = 2
group_rotation_frequency = 10


[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"
command = "polkadot"

    [[relaychain.node_groups]]
    name = "group1"
    image = "docker.io/parity/polkadot:latest"
    command = "polkadot"
    validator = true
    count = 3

    [[relaychain.node_groups]]
    name = "group2"
    image = "docker.io/parity/polkadot:latest"
    command = "polkadot"
    validator = true
    count = 2
    
[[relaychain.nodes]]
  name = "alice"
  args = [ "--alice", "-lruntime=debug,parachain=trace" ]

[[parachains]]
id = 100
addToGenesis = false
cumulus_based = false

  [[parachains.collators]]
  name = "collator01"
  image = "{{COL_IMAGE}}"
  command = "adder-collator"
  args = [ "-lruntime=debug,parachain=trace" ]

  [[parachains.collator_groups]]
  name = "collator_group"
  image = "{{COL_IMAGE}}"
  command = "adder-collator"
  args = [ "-lruntime=debug,parachain=trace" ]
  count = 2

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"