[settings]
timeout = 1000

[relaychain]
default_image = "docker.io/parity/polkadot:latest"
chain = "polkadot-local"
default_command = "polkadot"
chain_spec_runtime = { location = "https://github.com/polkadot-fellows/runtimes/releases/download/v1.9.3/polkadot_runtime-v1009003.compact.compressed.wasm", preset = "local_testnet" }

  [[relaychain.nodes]]
  name = "alice"
  args = [ "--alice", "-lruntime=debug,parachain=trace" ]

  [[relaychain.nodes]]
  name = "bob"
  args = [ "--bob", "-lruntime=debug,parachain=trace" ]

[[parachains]]
id = 100
chain="asset-hub-polkadot-local"
command="polkadot-omni-node"
chain_spec_runtime = { location = "https://github.com/polkadot-fellows/runtimes/releases/download/v1.9.2/asset-hub-polkadot_runtime-v1009002.compact.compressed.wasm", preset = "local_testnet" }
default_image= "docker.io/parity/polkadot-parachain:latest"

  [[parachains.collators]]
  name = "collator01"
  command = "polkadot-parachain"