stages:
  - integration-test

polkadot-integration-test:
  stage: integration-test
  image: paritytech/ci-unified:latest
  tags:
    - zombienet-polkadot-integration-test
  script:
    - kubectl get ns
  rules:
    - when: manual
