[settings]
timeout = 1000

[relaychain]
default_image = "docker.io/parity/polkadot:latest"
chain = "rococo-local"
default_command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  # Use -: prefix to remove the default insecure validator flag
  # This demonstrates the argument removal feature
  args = [ "-:--insecure-validator-i-know-what-i-do" ]
